# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POIsDB.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cPOIsDB.proto\"^\n\x03POI\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bobj_cell_id\x18\x02 \x01(\x04\x12\x10\n\x08origin_x\x18\x03 \x01(\x01\x12\x10\n\x08origin_y\x18\x04 \x01(\x01\x12\x10\n\x08origin_z\x18\x05 \x01(\x01\"\x1c\n\x06POIsDB\x12\x12\n\x04pois\x18\x01 \x03(\x0b\x32\x04.POIB\x15\n\x13io.ayoub.acdp.protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'POIsDB_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023io.ayoub.acdp.proto'
  _globals['_POI']._serialized_start=16
  _globals['_POI']._serialized_end=110
  _globals['_POISDB']._serialized_start=112
  _globals['_POISDB']._serialized_end=140
# @@protoc_insertion_point(module_scope)
